# https://taskfile.dev

version: '3'

env:
  GOBIN: go
  GO2GOTOOL: go tool go2go

vars:
  GOTESTFLAGS: -race -coverprofile=coverage.txt -covermode=atomic
  GOBENCHFLAGS: -bench=.
  PACKAGES: | 
    alg
    allocator
    iterator
    cache
    maps
    constraints
    list
    slices
    trees
    trees/binary
    stream
    testutil

tasks:
  default:
    deps: [test]

  translate:
    cmds:
      - cmd : |
          {{ $go_bin := default "go" .GOBIN -}}
          {{ $tool := default (cat $go_bin "tool go2go") .GO2GOTOOL -}}
          {{range $i, $line := .PACKAGES | splitLines }}{{ if $line -}} 
          {{ $splt := splitList "/" $line -}}
          {{ $tool }} translate ./{{ $line }}/{{ last $splt }}.go2 &&
          {{ $tool }} translate github.com/tdakkota/algo2/{{ $line }} &&
          {{ end }}{{ end -}}
          echo "complete!"

  clean:
    cmds:
      - cmd: | 
          {{ default "go" .GOBIN }} clean -testcache
      - ignore_error: true
        cmd : |
          {{range $i, $line := .PACKAGES | splitLines }} {{ if $line -}} 
          rm ./{{ $line }}/*.go
          {{ end }}{{ end -}}

  test:
    deps: [translate]
    cmds:
      - | 
        {{ default "go" .GOBIN }} test {{ .GOTESTFLAGS }} ./...

  bench:
    deps: [translate]
    cmds:
      - | 
        {{ default "go" .GOBIN }} test {{ .GOBENCHFLAGS }} ./...