# https://taskfile.dev

version: '3'

env:
  GOBIN: go

vars:
  PACKAGES: | 
    alg
    cache
    constraints
    list
    slices
    trees
    testutil

tasks:
  translate:
    cmds:
      - ignore_error: true
        cmd : |
          {{range $i, $line := .PACKAGES | splitLines }}{{ if $line -}} 
          $GOBIN tool go2go translate ./{{ $line }}/{{ $line }}.go2
          $GOBIN tool go2go translate github.com/tdakkota/algo2/{{ $line }}
          {{ end }}{{ end -}}

  clean:
    cmds:
      - ignore_error: true
        cmd : |
          {{range $i, $line := .PACKAGES | splitLines }} {{ if $line -}} 
          rm ./{{ $line }}/*.go
          {{ end }}{{ end -}}

  test:
    deps: [translate]
    cmds:
      - | 
        $GOBIN test -race ./...
