name: go2go

on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
        
    - name: Checkout dev.go2go 
      uses: actions/checkout@v2.3.4
      with:
        repository: golang/go
        ref: dev.go2go
        path: ${{ github.workspace }}/dev.go2go
      
    - name: Get lastest dev.go2go commit hash
      run: |
        cd ${{ github.workspace }}/dev.go2go/src  
        echo -e "go2go_commit_hash=$(git rev-parse HEAD)" >> $GITHUB_ENV

    - name: Cache dev.go2go build
      id: cache
      uses: actions/cache@v2.1.6
      with:
        path: ${{ github.workspace }}/dev.go2go
        key: ${{ runner.os }}-${{ env.go2go_commit_hash }}
      
    - name: Build dev.go2go
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        cd ${{ github.workspace }}/dev.go2go/src
        ./make.bash 

    - name: Add go2go to PATH
      run: |
        echo -e "${{ github.workspace }}/dev.go2go/bin\n$(cat $GITHUB_PATH)" > $GITHUB_PATH
        echo -e "${{ github.workspace }}/go2path/bin\n$(cat $GITHUB_PATH)" > $GITHUB_PATH

    - name: Install Taskfile
      run: |
        wget https://taskfile.dev/install.sh
        chmod +x ./install.sh
        ./install.sh -b ${{ github.workspace }}/go2path/bin
      
    - name: Check out code
      uses: actions/checkout@v2.3.4
      with:
        path: ./go2path/src/github.com/${{ github.repository }}
      
    - name: Test and bench
      env:
        GOROOT: ${{ github.workspace }}/dev.go2go
        GOPATH: ${{ github.workspace }}/go2path
        GO2PATH: ${{ github.workspace }}/go2path
        GO111MODULE: off
      run: |
        cd ./go2path/src/github.com/${{ github.repository }}
        task test
        task bench

    - name: Upload coverage to Codecov  
      uses: codecov/codecov-action@v2.0.2